services:
  db:
    image: postgres
    container_name: pg-spirit
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "54321:5432"

volumes:
  pg_data:
