version: '3.9'

services:
  db:
    image: postgres
    container_name: pg-spirit
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: pg-adminer-spirit
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pg_data:
